//Qs : Create an array to store companies -> "Bloomberg", "Microsoft", "Apple", "Amazon", "Google", "Meta" 
// a. remove first company using splice from array
// b. Remove "Amazon" from array and add aws in its place 
// c. Add "Facebook" at the end of the array


let arr=["Bloomberg","Microsoft","Apple","Amazon","Google","Meta"]


// a. remove first company using splice from array
arr.splice(0,1);
console.log(arr);


// b. Remove "Amazon" from array and add aws in its place 

arr.splice()